price_group:
  name:
    base: 'Base Rate'
    external: 'External Rate'
    cancer_center: 'Cancer Center Rate'

financial:
  # in the format MM-DD
  fiscal_year_begins: 09-01
  journal_format:
    xls: true
    csv: false
    xml: true

validator:
  class_name: NucsValidator
  test:
    factory: 'vendor/engines/nucs/spec/factories' # relative to Rails.root
    helper: 'vendor/engines/nucs/spec/support/nucs_validator_helper' # relative to Rails.root

email:
  from: 'nucore-noreply@northwestern.edu'
  fake:
    enabled: false
    to: 'john@tablexi.com'
  exceptions:
    sender: 'nucore-noreply@northwestern.edu'
    recipients: 'support-nucore@tablexi.com'

order_details:
  # These hooks are triggered when an order detail enters into the status
  # The hooks can be configured with settings. Here are several formats you can use:
  #   new:
  #     - ApprovalNotification::NotifyPurchaser
  #     - ApprovalNotification::NotifyFacility
  #   inprocess:
  #     -
  #       class: ApprovalNotification::NotifyPurchaser
  #       setting_1: test3
  #     - ApprovalNotification::NotifyFacility
  #   completed: ApprovalNotification::NotifyPurchaser
  #   reconciled: ["ApprovalNotification::NotifyPurchaser", "ApprovalNotification::NotifyFacility"]
  status_change_hooks:
    #pending_approval: StatusChangeNotifications::NotifyFacilityHook
    #approved: StatusChangeNotifications::NotifyPurchaserHook

reservations:
  grace_period: <%= 5.minutes %>

billing:
  review_period: <%= 7.days %>

external_services:
  survey: UrlService

relays:
  # can also be NetBooter::Telnet
  connect_module: NetBooter::Http
  test:
    admin_enabled: false
    reservation_enabled: false
  development:
    admin_enabled: false
    reservation_enabled: false
  staging:
    admin_enabled: true
    reservation_enabled: false
  production:
    admin_enabled: true
    reservation_enabled: true

# You should change this if you want to be able to access the API
api:
  basic_auth_name: <%= SecureRandom.hex %>
  basic_auth_password: <%= SecureRandom.hex %>

#
# For these settings use SettingsHelper#feature_on?
feature:
  create_users_on: true
  password_update_on: true
  recharge_accounts_on: true
  expense_accounts_on: true
  edit_accounts_on: true
  suspend_accounts_on: true
  product_specific_contacts_on: false
